/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../src/app/app.category';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../src/app/category/categoryService';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from 'primeng/components/datagrid/datagrid';
import * as import15 from '../../node_modules/primeng/components/datagrid/datagrid.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from 'primeng/components/common/shared';
import * as import18 from '../../node_modules/primeng/components/common/shared.ngfactory';
import * as import19 from '@angular/core/src/change_detection/change_detection_util';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import22 from 'primeng/components/panel/panel';
import * as import23 from '../../node_modules/primeng/components/panel/panel.ngfactory';
import * as import24 from '@angular/core/src/security';
export class Wrapper_AppCategory {
  /*private*/ _eventHandler:Function;
  context:import0.AppCategory;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.AppCategory(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppCategory_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppCategory_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppCategory>;
  _AppCategory_0_3:Wrapper_AppCategory;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppCategory_Host0,renderType_AppCategory_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'category-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppCategory0(this.viewUtils,this,0,this._el_0);
    this._AppCategory_0_3 = new Wrapper_AppCategory(this.injectorGet(import8.CategoryService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._AppCategory_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppCategory_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppCategory) && (0 === requestNodeIndex))) { return this._AppCategory_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppCategory_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppCategoryNgFactory:import7.ComponentFactory<import0.AppCategory> = new import7.ComponentFactory<import0.AppCategory>('category-app',View_AppCategory_Host0,import0.AppCategory);
const styles_AppCategory:any[] = ([] as any[]);
var renderType_AppCategory:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppCategory,{});
export class View_AppCategory0 extends import1.AppView<import0.AppCategory> {
  _anchor_0:any;
  /*private*/ _vc_0:import10.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import11.Wrapper_NgIf;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import10.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import11.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppCategory0,renderType_AppCategory,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import10.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import12.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import11.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_2 = new import10.ViewContainer(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import12.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import11.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1,
      this._anchor_2
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import13.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    if (((token === import12.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import13.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = (this.context.getLevel() > 0);
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    const currVal_2_0_0:any = (this.context.getLevel() == 0);
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this._vc_2.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 0)) { return new View_AppCategory1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    if ((nodeIndex == 2)) { return new View_AppCategory3(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_AppCategory1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import14.DataGrid>;
  _DataGrid_0_3:import15.Wrapper_DataGrid;
  _query_Header_0_0:import16.QueryList<any>;
  _query_Footer_0_1:import16.QueryList<any>;
  _query_PrimeTemplate_0_2:import16.QueryList<any>;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import17.Header>;
  _Header_2_3:import18.Wrapper_Header;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import10.ViewContainer;
  _TemplateRef_5_4:any;
  _PrimeTemplate_5_5:import18.Wrapper_PrimeTemplate;
  _text_6:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_AppCategory1,renderType_AppCategory,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_17 = import19.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'p-dataGrid',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_DataGrid0(this.viewUtils,this,0,this._el_0);
    this._DataGrid_0_3 = new import15.Wrapper_DataGrid(new import20.ElementRef(this._el_0),this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex));
    this._query_Header_0_0 = new import16.QueryList<any>();
    this._query_Footer_0_1 = new import16.QueryList<any>();
    this._query_PrimeTemplate_0_2 = new import16.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'p-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import18.View_Header0(this.viewUtils,this,2,this._el_2);
    this._Header_2_3 = new import18.Wrapper_Header();
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this.compView_2.create(this._Header_2_3.context);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_5 = new import10.ViewContainer(5,0,this,this._anchor_5);
    this._TemplateRef_5_4 = new import12.TemplateRef_(this,5,this._anchor_5);
    this._PrimeTemplate_5_5 = new import18.Wrapper_PrimeTemplate(this._TemplateRef_5_4);
    this._text_6 = this.renderer.createText((null as any),'\n',(null as any));
    this._query_Header_0_0.reset([this._Header_2_3.context]);
    this._DataGrid_0_3.context.header = this._query_Header_0_0.first;
    this._query_Footer_0_1.reset(([] as any[]));
    this._DataGrid_0_3.context.footer = this._query_Footer_0_1.first;
    this.compView_0.create(this._DataGrid_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.Header) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Header_2_3.context; }
    if (((token === import12.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_4; }
    if (((token === import17.PrimeTemplate) && (5 === requestNodeIndex))) { return this._PrimeTemplate_5_5.context; }
    if (((token === import14.DataGrid) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._DataGrid_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.getSubcategories();
    this._DataGrid_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._DataGrid_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._Header_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_5_0_0:any = 'item';
    this._PrimeTemplate_5_5.check_name(currVal_5_0_0,throwOnChange,false);
    this._PrimeTemplate_5_5.ngDoCheck(this,this._anchor_5,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_PrimeTemplate_0_2.dirty) {
        this._query_PrimeTemplate_0_2.reset([this._PrimeTemplate_5_5.context]);
        this._DataGrid_0_3.context.templates = this._query_PrimeTemplate_0_2;
        this._query_PrimeTemplate_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._DataGrid_0_3.context.ngAfterContentInit(); }
    }
    const currVal_17:any = import3.inlineInterpolate(1,'',this.parentView.context.getName(),'');
    if (import3.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_3,currVal_17);
      this._expr_17 = currVal_17;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._DataGrid_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_2.destroy();
    this._DataGrid_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._el_2,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._text_3,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 5)) { return new View_AppCategory2(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    return (null as any);
  }
}
class View_AppCategory2 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  compView_3:import1.AppView<import22.Panel>;
  _Panel_3_3:import23.Wrapper_Panel;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_AppCategory2,renderType_AppCategory,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_12 = import19.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','ui-g-12 ui-md-4'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'p-panel',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_3 = new import23.View_Panel0(this.viewUtils,this,3,this._el_3);
    this._Panel_3_3 = new import23.Wrapper_Panel(new import20.ElementRef(this._el_3));
    this._text_4 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'style','text-align: center; cursor:pointer'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n            ',(null as any));
    this.compView_3.create(this._Panel_3_3.context);
    this._text_8 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    this.init(this._text_9,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.Panel) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Panel_3_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Panel_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_12:any = import3.inlineInterpolate(1,'\n                    ',this.context.$implicit.name,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_6,currVal_12);
      this._expr_12 = currVal_12;
    }
    this.compView_3.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_3.destroy();
    this._Panel_3_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_9,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 3) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 3) && (ngContentIndex == 1))) {
      cb(this._text_4,ctx);
      cb(this._el_5,ctx);
      cb(this._text_7,ctx);
    }
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.navigate(((this.parentView.parentView.context.getLink() + '/') + this.parentView.parentView.context.toLink(this.context.$implicit.name)))) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_AppCategory3 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import14.DataGrid>;
  _DataGrid_0_3:import15.Wrapper_DataGrid;
  _query_Header_0_0:import16.QueryList<any>;
  _query_Footer_0_1:import16.QueryList<any>;
  _query_PrimeTemplate_0_2:import16.QueryList<any>;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import17.Header>;
  _Header_2_3:import18.Wrapper_Header;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import10.ViewContainer;
  _TemplateRef_4_4:any;
  _PrimeTemplate_4_5:import18.Wrapper_PrimeTemplate;
  _text_5:any;
  _el_6:any;
  compView_6:import1.AppView<import17.Footer>;
  _Footer_6_3:import18.Wrapper_Footer;
  _text_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_AppCategory3,renderType_AppCategory,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'p-dataGrid',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import15.View_DataGrid0(this.viewUtils,this,0,this._el_0);
    this._DataGrid_0_3 = new import15.Wrapper_DataGrid(new import20.ElementRef(this._el_0),this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex));
    this._query_Header_0_0 = new import16.QueryList<any>();
    this._query_Footer_0_1 = new import16.QueryList<any>();
    this._query_PrimeTemplate_0_2 = new import16.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'p-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import18.View_Header0(this.viewUtils,this,2,this._el_2);
    this._Header_2_3 = new import18.Wrapper_Header();
    this.compView_2.create(this._Header_2_3.context);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_4 = new import10.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_4 = new import12.TemplateRef_(this,4,this._anchor_4);
    this._PrimeTemplate_4_5 = new import18.Wrapper_PrimeTemplate(this._TemplateRef_4_4);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,(null as any),'p-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_6 = new import18.View_Footer0(this.viewUtils,this,6,this._el_6);
    this._Footer_6_3 = new import18.Wrapper_Footer();
    this.compView_6.create(this._Footer_6_3.context);
    this._text_7 = this.renderer.createText((null as any),'\n',(null as any));
    this._query_Header_0_0.reset([this._Header_2_3.context]);
    this._DataGrid_0_3.context.header = this._query_Header_0_0.first;
    this._query_Footer_0_1.reset([this._Footer_6_3.context]);
    this._DataGrid_0_3.context.footer = this._query_Footer_0_1.first;
    this.compView_0.create(this._DataGrid_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.Header) && (2 === requestNodeIndex))) { return this._Header_2_3.context; }
    if (((token === import12.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_4; }
    if (((token === import17.PrimeTemplate) && (4 === requestNodeIndex))) { return this._PrimeTemplate_4_5.context; }
    if (((token === import17.Footer) && (6 === requestNodeIndex))) { return this._Footer_6_3.context; }
    if (((token === import14.DataGrid) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._DataGrid_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.categories;
    this._DataGrid_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._DataGrid_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._Header_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = 'item';
    this._PrimeTemplate_4_5.check_name(currVal_4_0_0,throwOnChange,false);
    this._PrimeTemplate_4_5.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._Footer_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_PrimeTemplate_0_2.dirty) {
        this._query_PrimeTemplate_0_2.reset([this._PrimeTemplate_4_5.context]);
        this._DataGrid_0_3.context.templates = this._query_PrimeTemplate_0_2;
        this._query_PrimeTemplate_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._DataGrid_0_3.context.ngAfterContentInit(); }
    }
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_6.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._DataGrid_0_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_2.destroy();
    this.compView_6.destroy();
    this._DataGrid_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._el_2,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) { cb(this._el_6,ctx); }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 6) && (ngContentIndex == 0))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 4)) { return new View_AppCategory4(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}
class View_AppCategory4 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  compView_3:import1.AppView<import22.Panel>;
  _Panel_3_3:import23.Wrapper_Panel;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_AppCategory4,renderType_AppCategory,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_14 = import19.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','ui-g-12 ui-md-2'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'p-panel',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_3 = new import23.View_Panel0(this.viewUtils,this,3,this._el_3);
    this._Panel_3_3 = new import23.Wrapper_Panel(new import20.ElementRef(this._el_3));
    this._text_4 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'style','text-align: center'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n            ',(null as any));
    this.compView_3.create(this._Panel_3_3.context);
    this._text_10 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    this.init(this._text_11,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.Panel) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Panel_3_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.context.$implicit.name;
    this._Panel_3_3.check_header(currVal_3_0_0,throwOnChange,false);
    this._Panel_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_14:any = this.context.$implicit.icon;
    if (import3.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_7,'src',this.viewUtils.sanitizer.sanitize(import24.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    this.compView_3.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_3.destroy();
    this._Panel_3_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_11,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 3) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 3) && (ngContentIndex == 1))) {
      cb(this._text_4,ctx);
      cb(this._el_5,ctx);
      cb(this._text_9,ctx);
    }
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.navigate(this.parentView.parentView.context.toLink(this.context.$implicit.name))) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}